apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  labels:
    security.sotaria.io/type: "project"
  name: project-test-member
rules:
  - apiGroups: ["security.sotaria.io"]
    resources: ["projects"]
    verbs: ["get", "list", "watch"]

