apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.nfrush.github.com
spec:
  insecureSkipTLSVerify: true
  group: nfrush.github.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: api
    namespace: wardle
  version: v1alpha1
