apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.security.sotaria.io
spec:
  insecureSkipTLSVerify: true
  group: security.sotaria.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: api
    namespace: wardle
  version: v1alpha1
